### ISSUE TITLE
How do I define the Kiuwan credentials to be used?

### ISSUE THREAD

**Issue by lucasgros** [kiuwan/tfs-vsts-extension#1]

**Comment by jsalado** [comment]
Hi @lucasgros ,

Sorry for the delay answering this, we have had some issues with GitHub notifications.

You need to define the **KiuwanUser** and **KiuwanPasswd** variables in the builds that are using the extension's build tasks.

Make sure you use the latest version of the extension and version 2.* of the build tasks if you need to run builds in multi-platform agents.

**Comment by jsalado** [comment]
WE have published a new version of the extension that allows you create a new Service endpoint to Kiuwan where you specify credentials.

The tasks now will use those credentials. However if the KiuwanUser and KiuwanPasswd variables are defined in the build definition they will be used. This way you can override the credentials set at the service endpoint level.

You check the Kiuwan extension [marketplace page](https://marketplace.visualstudio.com/items?itemName=kiuwan-publisher.kiuwan-analysis-extension) to find out more.
