### ISSUE TITLE
Install kiuwan-publisher.kiuwan-analysis-extension-2.2015.2.vsix on TFS 2015

### ISSUE THREAD

**Issue by JesusGoVar** [kiuwan/tfs-vsts-extension#16]
It´s imposible install the kiwan.vsix in tfs 2015 relase 3, can you help me?

**Comment by jsalado** [comment]
Hello there,

Sorry you are experiencing problems. Can you please share more information? logs, error messages, etc.

I assume you downloaded the version for TFS 2015 from the specific link in the Kiuwan extension marketplace page.

**Comment by JesusGoVar** [comment]
Hi,
I dowload the vsix from this url
https://www.kiuwan.com/pub/tfs2015/kiuwan-publisher.kiuwan-analysis-extension-2.2015.1.vsix.zip

and this is the logs
02/01/2019 13:03:06 - Microsoft VSIX Installer
02/01/2019 13:03:06 - -------------------------------------------
02/01/2019 13:03:06 - vsixinstaller.exe version:
02/01/2019 13:03:06 - 15.0.26430.14 built by: D15SVC
02/01/2019 13:03:06 - -------------------------------------------
02/01/2019 13:03:06 - Command line parameters:
02/01/2019 13:03:06 - D:\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\jesusgo\Desktop\kiuwan-publisher.kiuwan-analysis-extension-2.2015.1.vsix (1)\kiuwan-publisher.kiuwan-analysis-extension-2.2015.3.vsix
02/01/2019 13:03:06 - -------------------------------------------
02/01/2019 13:03:06 - Microsoft VSIX Installer
02/01/2019 13:03:06 - -------------------------------------------
02/01/2019 13:03:06 - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
02/01/2019 13:03:07 - Initializing Install...
02/01/2019 13:03:07 - Extension Details...
02/01/2019 13:03:07 - 	Identifier         : kiuwan-analysis-extension
02/01/2019 13:03:07 - 	Name               : Kiuwan analysis
02/01/2019 13:03:07 - 	Author             : kiuwan-publisher
02/01/2019 13:03:07 - 	Version            : 2.2015.3
02/01/2019 13:03:07 - 	Description        : Analyze your applications with Kiuwan in your build definitions. Find relevant security vulnerabilities in your code. Run automatic code security audits. Build secure applications from the start.
02/01/2019 13:03:07 - 	Locale             : en-US
02/01/2019 13:03:07 - 	MoreInfoURL        : 
02/01/2019 13:03:07 - 	InstalledByMSI     : False
02/01/2019 13:03:07 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
02/01/2019 13:03:07 - 
02/01/2019 13:03:07 - 	SignatureState     : Unsigned
02/01/2019 13:03:07 - 	Supported Products : 
02/01/2019 13:03:07 - 		Microsoft.VisualStudio.Services
02/01/2019 13:03:07 - 			Version : [14.2,14.4]
02/01/2019 13:03:07 - 
02/01/2019 13:03:07 - 	References         : 
02/01/2019 13:03:07 - Signature Details...
02/01/2019 13:03:07 - 	Extension is not signed.
02/01/2019 13:03:07 - 
02/01/2019 13:03:07 - Searching for applicable products...
02/01/2019 13:03:07 - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
02/01/2019 13:03:07 - Found installed product - Microsoft Visual Studio Community 2015
02/01/2019 13:03:07 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
02/01/2019 13:03:07 - Found installed product - Global Location
02/01/2019 13:03:07 - Found installed product - Visual Studio Community 2017
02/01/2019 13:03:07 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Thanks

**Comment by jsalado** [comment]
Hello,

thanks for your feedback.

It seems that you are trying to install the vsix on a Visual Studio IDE... This extension is for Team Foundation Server 2015 update 2 or higher.

I have successfully installed it myself on a TFS 2015 update 3 uploading it to my server using the TFS administration interface.

**Comment by JesusGoVar** [comment]
I try again and everithings is ok
