### ISSUE TITLE
Kiuwan Results Tab Label Error

### ISSUE THREAD

**Issue by yairhdz** [kiuwan/tfs-vsts-extension#24]
Hi,

I am using extension in Azure DevOps and when it publish results to Kiuwan tab, it shows vulnerabilities and defects found in 'n' lines of code, however the number displayed correspond to the number of files i am scanning. 
 
![image](https://user-images.githubusercontent.com/15116006/73560632-f34e7600-441c-11ea-9eea-38d50b53dc4d.png)

It should be the same as shown in Kiuwan platform.

![image](https://user-images.githubusercontent.com/15116006/73561065-db2b2680-441d-11ea-9543-9e8243f05ff0.png)

Regards.

**Comment by luisgarciakiuwan** [comment]
Hi

Yes. You're right. we are displaying the number of files instead the lines of code. We will fix it and let you know.

Thanks
Luis

**Comment by kiuwan** [comment]
Solved.
