### ISSUE TITLE
Kiuwan Report in Build view like SonarQube

### ISSUE THREAD

**Issue by aldodfm** [kiuwan/tfs-vsts-extension#7]
Hello,

You can add a little view in Build view to see the result of the Kiuwan scan. Like Sonarqube or Checkmarks.

![sample1](https://user-images.githubusercontent.com/907559/38408203-d0588624-397c-11e8-863d-236f5af2d78e.png)
![2018-04-05_14h53_17](https://user-images.githubusercontent.com/907559/38408221-dc2a999c-397c-11e8-9acf-8e1d9c8e4ad0.png)

**Comment by kiuwan** [comment]
Implemented in relase v2.3.2 already in the Azure DevOps marketplace
